/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jcalculator;

import java.util.Locale;

/**
 *
 * @author miros
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    
    private boolean newOperation;
    private float score = 0;
    double first;
    double second;
    double result;
    String operation;
//    double num, ans;
//    int calculation;
    
    public Calculator() {
        initComponents();
    }
    
//    public void result(){
//        
//        {
//            switch(calculation){
//                
//                case 1:
//                    ans = num + Double.parseDouble(jTextField1.getText());
//                    jTextField1.setText(Double.toString(ans));
//                    break;
//                    
//                case 2:
//                    ans = num - Double.parseDouble(jTextField1.getText());
//                    jTextField1.setText(Double.toString(ans));
//                    break;
//                    
//                case 3:
//                    ans = num * Double.parseDouble(jTextField1.getText());
//                    jTextField1.setText(Double.toString(ans));
//                    break;
//                    
//                case 4:
//                    ans = num / Double.parseDouble(jTextField1.getText());
//                    jTextField1.setText(Double.toString(ans));
//                    break;
//                
//            }
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton300 = new javax.swing.JButton();
        jButton400 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton200 = new javax.swing.JButton();
        jButton600 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton1400 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButton1600 = new javax.swing.JButton();
        jButton1700 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton1601 = new javax.swing.JButton();
        jButton1701 = new javax.swing.JButton();
        jButton401 = new javax.swing.JButton();
        jButton201 = new javax.swing.JButton();
        jButton601 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JCalculator");
        setLocation(new java.awt.Point(500, 250));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setAutoscrolls(false);
        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton10.setText("√");
        jButton10.setMaximumSize(new java.awt.Dimension(42, 25));
        jButton10.setMinimumSize(new java.awt.Dimension(42, 25));
        jButton10.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton300.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton300.setText("%");
        jButton300.setMaximumSize(new java.awt.Dimension(42, 25));
        jButton300.setMinimumSize(new java.awt.Dimension(42, 25));
        jButton300.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton300.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton300ActionPerformed(evt);
            }
        });

        jButton400.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton400.setText("C");
        jButton400.setMaximumSize(new java.awt.Dimension(42, 25));
        jButton400.setMinimumSize(new java.awt.Dimension(42, 25));
        jButton400.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton400.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton400ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton12.setText("+/-");
        jButton12.setToolTipText("");
        jButton12.setMaximumSize(new java.awt.Dimension(42, 25));
        jButton12.setMinimumSize(new java.awt.Dimension(42, 25));
        jButton12.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton200.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton200.setText("-");
        jButton200.setMaximumSize(new java.awt.Dimension(42, 25));
        jButton200.setMinimumSize(new java.awt.Dimension(42, 25));
        jButton200.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton200ActionPerformed(evt);
            }
        });

        jButton600.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton600.setText("/");
        jButton600.setMaximumSize(new java.awt.Dimension(42, 25));
        jButton600.setMinimumSize(new java.awt.Dimension(42, 25));
        jButton600.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton600.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton600ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("5");
        jButton5.setMaximumSize(new java.awt.Dimension(42, 25));
        jButton5.setMinimumSize(new java.awt.Dimension(42, 25));
        jButton5.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setText("6");
        jButton6.setToolTipText("");
        jButton6.setMaximumSize(new java.awt.Dimension(42, 25));
        jButton6.setMinimumSize(new java.awt.Dimension(42, 25));
        jButton6.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("4");
        jButton4.setMaximumSize(new java.awt.Dimension(42, 25));
        jButton4.setMinimumSize(new java.awt.Dimension(42, 25));
        jButton4.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("2");
        jButton2.setMaximumSize(new java.awt.Dimension(42, 25));
        jButton2.setMinimumSize(new java.awt.Dimension(42, 25));
        jButton2.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("3");
        jButton3.setToolTipText("");
        jButton3.setMaximumSize(new java.awt.Dimension(42, 25));
        jButton3.setMinimumSize(new java.awt.Dimension(42, 25));
        jButton3.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("1");
        jButton1.setMaximumSize(new java.awt.Dimension(42, 25));
        jButton1.setMinimumSize(new java.awt.Dimension(42, 25));
        jButton1.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton11.setText(".");
        jButton11.setMaximumSize(new java.awt.Dimension(42, 25));
        jButton11.setMinimumSize(new java.awt.Dimension(42, 25));
        jButton11.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton1400.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1400.setText("=");
        jButton1400.setToolTipText("");
        jButton1400.setMaximumSize(new java.awt.Dimension(42, 25));
        jButton1400.setMinimumSize(new java.awt.Dimension(42, 25));
        jButton1400.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton1400.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1400ActionPerformed(evt);
            }
        });

        jButton0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton0.setText("0");
        jButton0.setMaximumSize(new java.awt.Dimension(42, 25));
        jButton0.setMinimumSize(new java.awt.Dimension(42, 25));
        jButton0.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        jButton1600.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1600.setText("+");
        jButton1600.setMaximumSize(new java.awt.Dimension(42, 25));
        jButton1600.setMinimumSize(new java.awt.Dimension(42, 25));
        jButton1600.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton1600.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1600ActionPerformed(evt);
            }
        });

        jButton1700.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1700.setText("*");
        jButton1700.setMaximumSize(new java.awt.Dimension(42, 25));
        jButton1700.setMinimumSize(new java.awt.Dimension(42, 25));
        jButton1700.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton1700.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1700ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton8.setText("8");
        jButton8.setMaximumSize(new java.awt.Dimension(42, 25));
        jButton8.setMinimumSize(new java.awt.Dimension(42, 25));
        jButton8.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton9.setText("9");
        jButton9.setToolTipText("");
        jButton9.setMaximumSize(new java.awt.Dimension(42, 25));
        jButton9.setMinimumSize(new java.awt.Dimension(42, 25));
        jButton9.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setText("7");
        jButton7.setMaximumSize(new java.awt.Dimension(42, 25));
        jButton7.setMinimumSize(new java.awt.Dimension(42, 25));
        jButton7.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton1601.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1601.setText("M+");
        jButton1601.setMaximumSize(new java.awt.Dimension(42, 25));
        jButton1601.setMinimumSize(new java.awt.Dimension(42, 25));
        jButton1601.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton1601.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1601ActionPerformed(evt);
            }
        });

        jButton1701.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1701.setText("MC");
        jButton1701.setMaximumSize(new java.awt.Dimension(42, 25));
        jButton1701.setMinimumSize(new java.awt.Dimension(42, 25));
        jButton1701.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton1701.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1701ActionPerformed(evt);
            }
        });

        jButton401.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton401.setText("CE");
        jButton401.setMaximumSize(new java.awt.Dimension(42, 25));
        jButton401.setMinimumSize(new java.awt.Dimension(42, 25));
        jButton401.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton401.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton401ActionPerformed(evt);
            }
        });

        jButton201.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton201.setText("M-");
        jButton201.setMaximumSize(new java.awt.Dimension(42, 25));
        jButton201.setMinimumSize(new java.awt.Dimension(42, 25));
        jButton201.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton201.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton201ActionPerformed(evt);
            }
        });

        jButton601.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton601.setText("MR");
        jButton601.setMaximumSize(new java.awt.Dimension(42, 25));
        jButton601.setMinimumSize(new java.awt.Dimension(42, 25));
        jButton601.setPreferredSize(new java.awt.Dimension(40, 25));
        jButton601.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton601ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1701, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1600, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton200, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1700, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton600, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1601, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton601, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton201, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton401, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton400, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton300, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1400, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1600, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton200, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1700, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton601, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1601, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton300, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1400, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton201, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton600, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton400, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton401, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1701, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        jTextField1.setText(jTextField1.getText() + "√"); 
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton300ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton300ActionPerformed
        jTextField1.setText(jTextField1.getText() + "%");
    }//GEN-LAST:event_jButton300ActionPerformed

    private void jButton400ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton400ActionPerformed
        jTextField1.setText("");
    }//GEN-LAST:event_jButton400ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        double dot = Double.parseDouble(String.valueOf(jTextField1.getText()));
        dot = dot * (-1);
        jTextField1.setText(String.valueOf(dot));
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton200ActionPerformed
        if(jTextField1.getText().isEmpty())
            return;
	if(operation != null){
            switch (operation) {
            case "-":
                score -= Float.parseFloat(jTextField1.getText());
                break;
		}
	}else{
		score = Float.parseFloat(jTextField1.getText());
		}
		jTextField1.setText("-");
                newOperation = true;
                operation = "-";
    }//GEN-LAST:event_jButton200ActionPerformed

    private void jButton600ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton600ActionPerformed
        if(jTextField1.getText().isEmpty())
            return;
	if(operation != null){
            switch (operation) {
            case "/":
                score /= Float.parseFloat(jTextField1.getText());
                break;
		}
	}else{
		score = Float.parseFloat(jTextField1.getText());
		}
		jTextField1.setText("/");
                newOperation = true;
                operation = "/";
    }//GEN-LAST:event_jButton600ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(newOperation == true){
            jTextField1.setText(jButton5.getText());
            newOperation = false;
	}else{
            jTextField1.setText(jButton5.getText());
            }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(newOperation == true){
            jTextField1.setText(jButton6.getText());
            newOperation = false;
	}else{
            jTextField1.setText(jButton6.getText());
            }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(newOperation == true){
            jTextField1.setText(jButton4.getText());
            newOperation = false;
	}else{
            jTextField1.getText();
            jTextField1.setText(jButton4.getText());
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(newOperation == true){
            jTextField1.setText(jButton2.getText());
            newOperation = false;
	}else{
            jTextField1.getText();
            jTextField1.setText(jButton2.getText());
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(newOperation == true){
            jTextField1.setText(jButton3.getText());
            newOperation = false;
	}else{
            jTextField1.setText(jButton3.getText());
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(newOperation == true){
            jTextField1.setText(jButton1.getText());
            newOperation = false;
	}else{
            jTextField1.setText(jButton1.getText());
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if(newOperation == true){
            jTextField1.setText("0.");
            newOperation = false;
	} else {
            String currentText = jTextField1.getText();
            if(currentText.indexOf(".") == -1){ // currentText.indexOf(".") != -1 thi bo qua
                jTextField1.setText(currentText + ".");
           }
	}
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton1400ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1400ActionPerformed
        if(jTextField1.getText().isEmpty())
	return;
	if(operation != null){
            switch (operation) {
                case "+":
                    score += Float.parseFloat(jTextField1.getText());
                    break;
		case "-":
                    score -= Float.parseFloat(jTextField1.getText());
                    break;
                case "*":
                    score *= Float.parseFloat(jTextField1.getText());
                    break;
		case "/":
                    score /= Float.parseFloat(jTextField1.getText());
                    break;
		}
		}else{
                    score = Float.parseFloat(jTextField1.getText());
		}
	jTextField1.setText(String.valueOf(score));
	newOperation = true;
	operation = null;
    }//GEN-LAST:event_jButton1400ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        if(newOperation != true){
            jTextField1.setText(jButton0.getText());
        }else{
            jTextField1.setText(jButton0.getText());
            }
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButton1600ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1600ActionPerformed
        if(jTextField1.getText().isEmpty())
            return;
	if(operation != null){
            switch (operation) {
            case "+":
                score += Float.parseFloat(jTextField1.getText());
                break;
		}
	}else{
		score = Float.parseFloat(jTextField1.getText());
		}
		jTextField1.setText("+");
                newOperation = true;
                operation = "+";
    }//GEN-LAST:event_jButton1600ActionPerformed

    private void jButton1700ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1700ActionPerformed
        if(jTextField1.getText().isEmpty())
            return;
	if(operation != null){
            switch (operation) {
            case "*":
                score *= Float.parseFloat(jTextField1.getText());
                break;
		}
	}else{
		score = Float.parseFloat(jTextField1.getText());
		}
		jTextField1.setText("*");
                newOperation = true;
                operation = "*";
    }//GEN-LAST:event_jButton1700ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(newOperation == true){
            jTextField1.setText(jButton8.getText());
            newOperation = false;
	}else{
            jTextField1.setText(jButton8.getText());
            }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if(newOperation == true){
            jTextField1.setText(jButton9.getText());
            newOperation = false;
	}else{
            jTextField1.setText(jButton9.getText());
            }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(newOperation == true){
            jTextField1.setText(jButton7.getText());
            newOperation = false;
	}else{
            jTextField1.setText(jButton7.getText());
            }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1601ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1601ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1601ActionPerformed

    private void jButton1701ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1701ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1701ActionPerformed

    private void jButton401ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton401ActionPerformed
        int length = jTextField1.getText().length();
        int number = jTextField1.getText().length() - 1;
        
        String store;
        
        if(length > 0){
            
            StringBuilder back = new StringBuilder(jTextField1.getText());
            back.deleteCharAt(number);
            store = back.toString();
            jTextField1.setText(store);
        }
    }//GEN-LAST:event_jButton401ActionPerformed

    private void jButton201ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton201ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton201ActionPerformed

    private void jButton601ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton601ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton601ActionPerformed

    private void jLabel18ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        jTextField1.setText(jTextField1.getText() + "1");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton1400;
    private javax.swing.JButton jButton1600;
    private javax.swing.JButton jButton1601;
    private javax.swing.JButton jButton1700;
    private javax.swing.JButton jButton1701;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton200;
    private javax.swing.JButton jButton201;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton300;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton400;
    private javax.swing.JButton jButton401;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton600;
    private javax.swing.JButton jButton601;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
